# volumes/vol1.conf
PDF_TITLE="Arliz: Zero to Bit"
PDF_TITLE_FRONT="Arliz Vol. I"
PDF_COVER_TITLE="Arliz"
PDF_SUBJECT="Volume I -- Zero to Bit"
PDF_KEYWORDS="arrays, computer science, data representation"

FRONTMATTER_DIR="frontmatter/vol1"
MAIN_FRONTMATTER="frontmatter/"
PARTS=(
  "parts/part01/part01"
)

BACKMATTER=(
  "backmatter/vol1/backmatter"
  "backmatter/vol1/note"
)

VOLUME_NUM=1
VOLUME_TITLE="Zero_to_Bit"

COVER_IMAGE="covers/cover-vol1.jpg"