# volumes/vol2.conf
PDF_TITLE="Arliz: Silicon Horizon"
PDF_TITLE_FRONT="Arliz Vol. II"
PDF_COVER_TITLE="Arliz"
PDF_SUBJECT="Volume II -- Silicon Horizon"
PDF_KEYWORDS="arrays, computer architecture, hardware"

FRONTMATTER_DIR="frontmatter/vol2"

PARTS=(
  "parts/part02/part02"
)

BACKMATTER=(
  "backmatter/vol2/backmatter"
)

PDF_OUTPUT="Arliz-Vol2.pdf"
COVER_IMAGE="covers/cover-vol1.jpg"