# volumes/vol3.conf
PDF_TITLE="Arliz: Array Odyssey"
PDF_TITLE_FRONT="Arliz Vol. III"
PDF_COVER_TITLE="Arliz"
PDF_SUBJECT="Volume III -- Array Odyssey"
PDF_KEYWORDS="arrays, data structures, algorithms"

FRONTMATTER_DIR="frontmatter/vol3"

PARTS=(
  "parts/part03/part03"
)

BACKMATTER=(
  "backmatter/vol3/backmatter"
)

PDF_OUTPUT="Arliz-Vol3.pdf"
COVER_IMAGE="covers/cover-vol3.jpg"